# Create New Protocol Version and Trigger Propagation
# Usage: ./scripts/release-protocol.ps1 -Version "3.1.0" -Type "patch"

param(
    [Parameter(Mandatory=$false)]
    [string]$Version = "",

    [Parameter(Mandatory=$false)]
    [ValidateSet("major", "minor", "patch")]
    [string]$Type = "patch",

    [Parameter(Mandatory=$false)]
    [string]$Message = "",

    [Parameter(Mandatory=$false)]
    [ValidateSet("workflows", "agents", "scripts", "full")]
    [string]$UpdateType = "workflows",

    [Parameter(Mandatory=$false)]
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

Write-Host "🚀 Git-Core Protocol Release Manager" -ForegroundColor Cyan
Write-Host ""

# Leer versión actual
$currentVersion = Get-Content VERSION -ErrorAction SilentlyContinue
if (-not $currentVersion) {
    $currentVersion = "3.0.0"
    $currentVersion | Out-File VERSION -NoNewline
}

Write-Host "📦 Current Version: v$currentVersion" -ForegroundColor Yellow

# Calcular nueva versión si no se especificó
if (-not $Version) {
    $parts = $currentVersion -split '\.'
    $major = [int]$parts[0]
    $minor = [int]$parts[1]
    $patch = [int]$parts[2]

    switch ($Type) {
        "major" { $major++; $minor = 0; $patch = 0 }
        "minor" { $minor++; $patch = 0 }
        "patch" { $patch++ }
    }

    $Version = "$major.$minor.$patch"
}

Write-Host "🎯 New Version: v$Version" -ForegroundColor Green
Write-Host "📝 Update Type: $UpdateType" -ForegroundColor Cyan

if ($DryRun) {
    Write-Host "`n[DRY RUN MODE - No changes will be made]" -ForegroundColor Gray
    Write-Host ""
    Write-Host "Would execute:" -ForegroundColor Yellow
    Write-Host "  1. Update VERSION file to $Version"
    Write-Host "  2. Commit changes"
    Write-Host "  3. Create tag v$Version"
    Write-Host "  4. Push tag (triggers propagation to all repos)"
    Write-Host "  5. Propagation workflow creates PRs in:"
    Write-Host "     - software-factory"
    Write-Host "     - domus-otec"
    Write-Host "     - less-colegio"
    Write-Host "     - synapse-protocol"
    Write-Host "     - gara-g"
    Write-Host "     - gastronomic-open-standard-GOS"
    Write-Host "     - contratafacil"
    Write-Host "     - bestof-opensorce"
    Write-Host "     - obs-studio-agent"
    Write-Host "     - pocket_cerebro"
    exit 0
}

# Confirmar
Write-Host ""
Write-Host "⚠️  This will:" -ForegroundColor Yellow
Write-Host "   1. Update VERSION to $Version"
Write-Host "   2. Create and push tag v$Version"
Write-Host "   3. Trigger propagation to ALL repositories"
Write-Host ""
$confirm = Read-Host "Continue? (yes/no)"
if ($confirm -ne "yes") {
    Write-Host "❌ Aborted" -ForegroundColor Red
    exit 1
}

# Verificar que estamos en main y está limpio
$branch = git branch --show-current
if ($branch -ne "main") {
    Write-Host "❌ Must be on main branch (current: $branch)" -ForegroundColor Red
    exit 1
}

$status = git status --porcelain
if ($status) {
    Write-Host "❌ Working directory not clean. Commit or stash changes first." -ForegroundColor Red
    Write-Host $status
    exit 1
}

# Pull latest
Write-Host "📥 Pulling latest changes..." -ForegroundColor Cyan
git pull origin main

# Actualizar VERSION
Write-Host "📝 Updating VERSION file..." -ForegroundColor Cyan
$Version | Out-File VERSION -NoNewline

# Commit
$commitMsg = if ($Message) { $Message } else { "chore: bump version to v$Version" }
Write-Host "💾 Committing..." -ForegroundColor Cyan
git add VERSION
git commit -m $commitMsg

# Crear tag
Write-Host "🏷️  Creating tag v$Version..." -ForegroundColor Cyan
$tagMsg = "Git-Core Protocol v$Version

Release type: $Type
Update scope: $UpdateType

Auto-generated by release-protocol.ps1"

git tag -a "v$Version" -m $tagMsg

# Push commit y tag
Write-Host "📤 Pushing to remote..." -ForegroundColor Cyan
git push origin main
git push origin "v$Version"

Write-Host ""
Write-Host "✅ Release v$Version created successfully!" -ForegroundColor Green
Write-Host ""
Write-Host "📊 Next steps:" -ForegroundColor Cyan
Write-Host "   1. Monitor workflow: https://github.com/iberi22/Git-Core-Protocol/actions"
Write-Host "   2. Propagation will create PRs in all target repos"
Write-Host "   3. Review and merge PRs in each repo"
Write-Host ""
Write-Host "🔗 View release: https://github.com/iberi22/Git-Core-Protocol/releases/tag/v$Version"
